make: import_cfgmake "core.cfg",
python: import_cfgmake "python.cfg",
c: (import_cfgmake "c.cfg").context {
  cc: "gcc",
  cflags: ["-O2", "-wall"],
},

targets: {
  python_conflag: python.library {
    sources: ["conflag.py"],
    dependencies: [ply],
  },
  ply: python.pypi "ply",

  clean: make.clean,

  conflag: c.binary {
    name: "conflag",
    dependencies: [
      parser,
      lexer,
    ],
  },

  lexer: c.library {
    name: "lex.yy",
    dependencies: [
      make.cmd ["flex", "conflag.l"],
      parser,
    ],
  },

  parser: c.library {
    name: "conflag.tab",
    dependencies: [
      make.cmd ["bison", "-d", "-v", "conflag.y"],
    ],
  },

  bison: make.target {
    filename version: "bison-" + version + ".tar.xz",
    version: "3.0",
    dependencies: [
      make.ftp ("ftp.gnu.org/gnu/bison/" + (filename version)) "build/tmp/",
      make.cmd ["tar", "-xJf", "build/tmp/" + (filename version)],
    ],
  },
},
