name: CI Tests

# This workflow run tests and build for each push

on:
  push:
    branches:
      - master
      - 'feature-**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly          

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: List Features
        id: list-features
        run: |
          echo ::set-output name=features::$(cargo read-manifest | jq '.features')

      - name: Lint
        run: |
          cd conflag
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test Default Features
        run: |
          cd conflag
          cargo check
          cargo test --all

      - name: Test No Features
        run: |
          cd conflag
          cargo check --no-default-features
          cargo test --all --no-default-features

      - name: Test All Features
        run: |
          cd conflag
          cargo check --all-features
          cargo test --all --all-features

      - name: Test Each Feature
        run: |
          cd conflag
          for feature in $(cargo read-manifest | jq -r '.features | keys[]'); do
            printf '\n\n\n---------------------------------------------------------------------------'
            printf "\nn\t TESTING FEATURE: $feature\n\n"
            cargo check --features $feature
            cargo test --all --features $feature
          done

      - name: Build
        run: |
          cd conflag
          cargo build --release  
